# **🧼🫧🧹 Data Cleaning**

<img src="assets/banner_preliminary_cleaning.jpg" style="width:90%">

- Data cleaning is of paramount importance in the machine learning lifecycle.

- A survey by Anaconda found that data cleaning takes up to **40% of the total time spent** in a typical machine learning project.

- This significant investment of time underscores its critical role in ensuring the success and reliability of machine learning models.

- Data cleaning is a crucial part of the data preprocessing phase in any machine learning project.

- Ensuring that data is clean and ready for analysis involves several key steps.

- Three critical steps in this process are **correcting structural errors, handling missing values, and removing unnecessary or unwanted data**.

- Each of these steps plays a vital role in enhancing the quality and reliability of the data, ultimately leading to better model performance and more accurate insights.

| Benefit                      | Explanation                                                                                                                    |
|--------------------------------|-----------------------------------------------------------------------------------------------------------------------------------|
| **Improves Data Quality 🧹**   | - Raw data often contains errors, inconsistencies, and inaccuracies. <br> - Cleaning data involves identifying and correcting these issues. <br> - Ensures accuracy, consistency, and reliability. |
| **Enhances Model Performance 🤖** | - Machine learning models are only as good as the data they are trained on. <br> - Clean data helps models generalize better by removing noise and irrelevant information. <br> - Improves predictive accuracy. |
| **Reduces Bias and Variance ⚖️** | - Dirty data can introduce bias and variance. <br> - This can lead to overfitting or underfitting. <br> - Cleaning data reduces these risks, making models more robust and reliable. |
| **Facilitates Data Integration 🔗** | - Data often comes from multiple sources. <br> - Cleaning ensures smooth integration across systems. <br> - Enables comprehensive analysis when combining datasets. |
| **Ensures Compliance and Data Governance 🛡️** | - Data cleaning enforces compliance with regulatory standards. <br> - Supports internal data governance policies. <br> - Critical in industries like healthcare and finance where data integrity is essential. |

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

---
---
---
# **🧼 General Cleaning**

- Perform basic data cleaning to improve consistency and prepare the dataset for analysis.

- Ensures the data is easier to work with and less error-prone.

---
---
## └─ **Apply snake-case**

- Using `snake_case` aligns with PEP 8, Python’s official style guide for code readability and consistency.

- It ensures column names are consistent and easy to read, avoiding spaces or special characters that can break code.

- Standardized naming makes data manipulation, merging, and referencing columns in scripts much smoother.

- Following PEP 8 conventions improves code maintainability, readability, and reduces potential errors in data pipelines.

**🧩 Function**

In [2]:
import re
import pandas as pd

def convert_column_names_to_snake_case(df: pd.DataFrame) -> pd.DataFrame:
    """
    Convert all column names in a DataFrame to snake_case.

    This function:
    - Converts all letters to lowercase.
    - Strips leading/trailing whitespace.
    - Replaces spaces with underscores.
    - Removes all non-alphanumeric characters except underscores.

    Parameters:
        df (pd.DataFrame): The input DataFrame whose columns will be converted.

    Returns:
        pd.DataFrame: A new DataFrame with snake_case column names.
    """
    print("   └── Converting column names to snake_case...")

    def to_snake_case(text: str) -> str:
        text = text.lower().strip()
        text = re.sub(r'\s+', '_', text)          # Replace spaces with underscore
        text = re.sub(r'[^a-z0-9_]', '', text)    # Remove special characters
        text = re.sub(r'_+', '_', text)           # Collapse multiple underscores
        text = text.strip('_')                    # Remove leading/trailing underscores
        return text

    df = df.copy()
    df.columns = [to_snake_case(col) for col in df.columns]
    return df

**⚙️ Implementation**

In [3]:
df_sample = pd.DataFrame({
    'First Name': ['Alice', 'Bob', 'Charlie'],
    'Last Name': ['Smith', 'Jones', 'Brown'],
    'Favorite Color': ['Blue', 'Green', 'Red'],
    'Year of Birth': [1990, 1985, 1978]
})

df_sample = convert_column_names_to_snake_case(df_sample)
df_sample.head()

   └── Converting column names to snake_case...

  first_name last_name favorite_color  year_of_birth
0      Alice     Smith           Blue           1990
1        Bob     Jones          Green           1985
2    Charlie     Brown            Red           1978

---
---
## └─ **Convert data type**

**🧩 Function**

In [4]:
import pandas as pd
from typing import Dict, Any

def convert_columns_dtype(df: pd.DataFrame, columns_types: Dict[str, Any]) -> pd.DataFrame:
    """
    Convert specified columns in a DataFrame to the desired data types.

    Supported dtypes:
    - 'numeric'  : converts to numeric values (coerces errors to NaN)
    - 'category' : converts to categorical type
    - 'string'   : converts to string type
    - 'datetime' : converts to datetime (coerces errors to NaT)
    - Any valid pandas dtype (e.g., 'int', 'float', 'bool') is also supported.

    Parameters:
        df (pd.DataFrame): Input DataFrame to convert.
        columns_types (dict): A dictionary mapping column names to target dtypes.

    Returns:
        pd.DataFrame: A new DataFrame with columns converted to specified data types.
    """
    df = df.copy()

    for col, dtype in columns_types.items():
        if col not in df.columns:
            print(f"   └── ⚠️ Warning: Column '{col}' not found in DataFrame. Skipping.")
            continue

        print(f"   └── Converting column '{col}' to '{dtype}'")

        try:
            if dtype == 'numeric':
                df[col] = pd.to_numeric(df[col], errors='coerce')
            elif dtype == 'category':
                df[col] = df[col].astype('category')
            elif dtype == 'string':
                df[col] = df[col].astype('string')
            elif dtype == 'datetime':
                df[col] = pd.to_datetime(df[col], errors='coerce')
            else:
                df[col] = df[col].astype(dtype)
        except Exception as e:
            print(f"   └── ⚠️ Warning: Could not convert column '{col}' to '{dtype}': {e}")

    return df

**⚙️ Implementation**

In [5]:
df_sample = pd.DataFrame({
    'age': ['25', '30', '35', '40', 'not available'],
    'gender': ['Male', 'Female', 'Female', 'Male', 'Female'],
    'signup_date': ['2023-01-10', '2023-02-15', '2023-03-20', 'not a date', '2023-05-01'],
    'score': ['88.5', '92.3', '85.0', '90.2', '87.7'],
    'user_id': [101, 102, 103, 104, 105]
})

df_sample = convert_columns_dtype(df_sample, {
    'age': 'numeric',
    'gender': 'category',
    'signup_date': 'datetime',
    'random_column': 'datetime',  
    # 'score': 'float',
    # 'user_id': 'string'
})
df_sample.dtypes

   └── Converting column 'age' to 'numeric'
   └── Converting column 'gender' to 'category'
   └── Converting column 'signup_date' to 'datetime'
   └── ⚠️ Warning: Column 'random_column' not found in DataFrame. Skipping.

age                   float64
gender               category
signup_date    datetime64[ns]
score                  object
user_id                 int64
dtype: object

---
---
## └─ **Re-arrange columns**

In [6]:
import pandas as pd

def move_column_before(df: pd.DataFrame, col_to_move: str, before_col: str) -> pd.DataFrame:
    """
    Rearrange the order of columns in a DataFrame by moving a specific column
    before another specified column.

    Parameters
    ----------
    df : pd.DataFrame
        Input DataFrame.
    col_to_move : str
        The name of the column to move.
    before_col : str
        The name of the column before which `col_to_move` should be placed.

    Returns
    -------
    pd.DataFrame
        A new DataFrame with columns rearranged.
    """
    print(f"   └── Moving column '{col_to_move}' before '{before_col}'...")

    if col_to_move not in df.columns:
        raise ValueError(f"Column '{col_to_move}' not found in DataFrame.")
    if before_col not in df.columns:
        raise ValueError(f"Column '{before_col}' not found in DataFrame.")
    if col_to_move == before_col:
        return df  # nothing to do

    cols = list(df.columns)
    cols.remove(col_to_move)  # take out the column
    insert_at = cols.index(before_col)
    cols.insert(insert_at, col_to_move)  # put it back before target column

    return df[cols]

In [7]:
data = {
    "A": [1, 2, 3],
    "B": [4, 5, 6],
    "C": [7, 8, 9]
}
df = pd.DataFrame(data)

# Move column "C" before "B"
df_new = move_column_before(df, "C", "B")
print(df_new)

   └── Moving column 'C' before 'B'...
   A  C  B
0  1  7  4
1  2  8  5
2  3  9  6

---
---
---
# **🧼 Unnecessary Data**

- Not all data in a dataset is useful for analysis.

- Removing unnecessary or unwanted data helps streamline the dataset and focus on the most relevant information.

- By removing unnecessary or unwanted data, we enhance the clarity and focus of the dataset, making it more suitable for analysis and modeling.

- Before removing any data, it is important to have sound justifications for doing so.

---
---
## └─ **Drop irrelevant features**

- Removing columns that do not contribute to the analysis or model.

- For example, an ID column may not be relevant for predicting customer behavior.

- **Dropping Post-hoc Features**: Removing columns that will not be available at the time of prediction, sometimes referred to as post-hoc or leaky data. Including them in the model would be like using information from the future - it would make our model seem more accurate than it really is. For example, since we are predicting the 'resale_price' of HDB flats, we should exclude features like 'resale_price_USD', as this is just a converted version of the target variable and won’t be available during prediction. Removing such features will prevent data leakage and ensure the model’s performance is realistic and reliable.

**🧩 Function**

In [8]:
def drop_irrelevant_features(df, columns_to_drop):
    """
    Drops specified irrelevant columns from a DataFrame.
    
    Parameters:
        df (pd.DataFrame): The input DataFrame.
        columns_to_drop (list): List of column names to drop.
    
    Returns:
        pd.DataFrame: A new DataFrame with specified columns removed.
    """
    if columns_to_drop:
        print(f"   └── Dropping irrelevant columns: {columns_to_drop}")
    else:
        print("   └── No columns specified to drop.")
    
    df = df.copy()
    df = df.drop(columns=columns_to_drop, errors='ignore')
    return df

**⚙️ Implementation**

In [9]:
df_sample = pd.DataFrame({
    'age': [25, 30, 22],
    'name': ['Alice', 'Bob', 'Charlie'],
    'salary': [50000, 60000, 45000],
    'random_col': [1, 2, 3]
})

df_sample = drop_irrelevant_features(df_sample, columns_to_drop=['random_col', 'name'])
df_sample

   └── Dropping irrelevant columns: ['random_col', 'name']

   age  salary
0   25   50000
1   30   60000
2   22   45000

---
---
## └─ **Drop duplicate rows**

- Identifying and removing duplicate rows to avoid redundancy and ensure that each data point is unique.

**🧩 Function**

In [10]:
import pandas as pd
from typing import Optional, List

def drop_duplicates(df: pd.DataFrame, subset: Optional[List[str]] = None) -> pd.DataFrame:
    """
    Remove duplicate rows from a DataFrame.

    Parameters:
        df (pd.DataFrame): Input DataFrame.
        subset (list of str, optional): Columns to consider when identifying duplicates.
            - If None, all columns are used.

    Returns:
        pd.DataFrame: A new DataFrame with duplicates removed.
    
    Notes:
        - The original DataFrame is not modified.
        - Logs which columns are used for duplicate removal.
    """
    if subset:
        print(f"   └── Dropping duplicates based on subset columns: {subset}")
    else:
        print("   └── Dropping duplicates based on all columns...")

    df = df.copy()
    df = df.drop_duplicates(subset=subset)
    return df

**⚙️ Implementation**

In [11]:
df_sample = pd.DataFrame({
    'id': [1, 2, 2, 3, 4, 4, 5],
    'name': ['Alice', 'Bob', 'Bob', 'Charlie', 'David', 'David', 'Eve'],
    'age': [25, 30, 30, 35, 40, 40, 45]
})

df_sample = drop_duplicates(df_sample, subset=['id', 'name'])
df_sample

   └── Dropping duplicates based on subset columns: ['id', 'name']

   id     name  age
0   1    Alice   25
1   2      Bob   30
3   3  Charlie   35
4   4    David   40
6   5      Eve   45

---
---
## └─ **Filter irrelevant rows**

- Removing rows that do not fit the context of the analysis.

- For example, excluding data from a specific time period that is not relevant to the study.

**🧩 Function**

In [12]:
import pandas as pd

def filter_irrelevant_rows(df: pd.DataFrame, condition: callable, description: str = "") -> pd.DataFrame:
    """
    Remove rows that do not fit the context of the analysis based on a condition.

    Parameters:
        df (pd.DataFrame): Input DataFrame.
        condition (callable): A function that takes the DataFrame and returns a boolean Series indicating rows to keep.
        description (str): Optional description of the filter for logging.

    Returns:
        pd.DataFrame: A new DataFrame with irrelevant rows removed.
    
    Notes:
        - The original DataFrame is not modified.
        - Logs the number of rows removed.
    """
    df = df.copy()
    before_rows = len(df)
    df = df[condition(df)]
    removed = before_rows - len(df)
    desc_text = f" ({description})" if description else ""
    print(f"   └── Removed {removed} irrelevant rows{desc_text}.")
    return df

**⚙️ Implementation**

In [13]:
# Sample dataset
df = pd.DataFrame({
    'date': pd.to_datetime(['2022-01-01','2022-02-01','2022-03-01','2021-12-01']),
    'sales': [100, 150, 200, 50]
})

# Remove rows not in 2022
df_clean = filter_irrelevant_rows(
    df,
    condition=lambda x: x['date'].dt.year == 2022,
    description="keeping only year 2022"
)
df_clean

   └── Removed 1 irrelevant rows (keeping only year 2022).

        date  sales
0 2022-01-01    100
1 2022-02-01    150
2 2022-03-01    200

---
---
## └─ **Drop duplicate ID's**

- Eliminating outliers or data points that do not represent the typical behavior or distribution of the dataset, which can distort analysis and model training.

---
---
## └─ **Remove outliers**

- Eliminating outliers or data points that do not represent the typical behavior or distribution of the dataset, which can distort analysis and model training.

**🧩 Function**

In [14]:
import pandas as pd

def remove_outliers(df: pd.DataFrame, columns: list, method: str = 'iqr', factor: float = 1.5) -> pd.DataFrame:
    """
    Remove outliers from specified numeric columns in a DataFrame.

    Parameters:
        df (pd.DataFrame): Input DataFrame.
        columns (list): List of numeric columns to check for outliers.
        method (str): Method to detect outliers. Currently supports:
            - 'iqr' (default): Interquartile Range method.
        factor (float): Multiplier for IQR to define outlier thresholds (default=1.5).

    Returns:
        pd.DataFrame: A new DataFrame with outliers removed.
    
    Notes:
        - The original DataFrame is not modified.
        - Logs the number of rows removed per column.
    """
    df = df.copy()
    
    for col in columns:
        if col not in df.columns:
            print(f"      ! Warning: Column '{col}' not found. Skipping.")
            continue
        if not pd.api.types.is_numeric_dtype(df[col]):
            print(f"      ! Warning: Column '{col}' is not numeric. Skipping.")
            continue

        if method == 'iqr':
            Q1 = df[col].quantile(0.25)
            Q3 = df[col].quantile(0.75)
            IQR = Q3 - Q1
            lower_bound = Q1 - factor * IQR
            upper_bound = Q3 + factor * IQR
            before_rows = len(df)
            df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]
            removed = before_rows - len(df)
            print(f"   └── Removed {removed} outliers from '{col}' using IQR method.")
        else:
            print(f"      ! Warning: Method '{method}' not recognized. Skipping column '{col}'.")
    
    return df

**⚙️ Implementation**

In [15]:
# Sample dataset
df_sample = pd.DataFrame({
    'age': [25, 30, 22, 120, 27, 35, 28],  # 120 is an outlier
    'salary': [50000, 60000, 45000, 700000, 52000, 58000, 54000]  # 700000 is an outlier
})

# Remove outliers
df_clean = remove_outliers(df_sample, columns=['age', 'salary'])
df_clean

   └── Removed 1 outliers from 'age' using IQR method.
   └── Removed 0 outliers from 'salary' using IQR method.

   age  salary
0   25   50000
1   30   60000
2   22   45000
4   27   52000
5   35   58000
6   28   54000

---
---
---
# **🧼 Missing Values**

- Not all data in a dataset is useful for analysis.

- Removing unnecessary or unwanted data helps streamline the dataset and focus on the most relevant information.

---
---
## └─ **Mark missing values**

In [16]:
import pandas as pd
from typing import List, Union

def mark_missing_values(
    df: pd.DataFrame,
    numerical_columns: List[str] = [],
    categorical_columns: List[str] = [],
    numerical_placeholder: Union[int, float] = 999,
    categorical_placeholder: str = 'missing'
) -> pd.DataFrame:
    """
    Impute missing values in numerical and categorical columns with specified placeholders.

    Parameters:
        df (pd.DataFrame): Input DataFrame.
        numerical_columns (list): List of numerical columns to impute.
        categorical_columns (list): List of categorical columns to impute.
        numerical_placeholder (int/float): Value to replace missing numerical data (default=999).
        categorical_placeholder (str): Value to replace missing categorical data (default='missing').

    Returns:
        pd.DataFrame: A new DataFrame with missing values imputed.
    
    Notes:
        - The original DataFrame is not modified.
        - Logs which columns are being imputed.
    """
    df = df.copy()

    # Handle numerical columns
    if numerical_columns:
        print(f"   └── Imputing missing values in numerical columns: {numerical_columns} with placeholder: {numerical_placeholder}")
        for col in numerical_columns:
            if col in df.columns and df[col].isnull().any():
                df[col] = df[col].fillna(numerical_placeholder)

    # Handle categorical columns
    if categorical_columns:
        print(f"   └── Imputing missing values in categorical columns: {categorical_columns} with placeholder: '{categorical_placeholder}'")
        for col in categorical_columns:
            if col in df.columns:
                df[col] = df[col].astype('object')  # ensure consistent dtype
                df[col] = df[col].fillna(categorical_placeholder)

    return df

In [17]:
import pandas as pd
import numpy as np

# Sample DataFrame
df_sample = pd.DataFrame({
    'age': [25, 30, np.nan, 40, np.nan],
    'income': [50000, 60000, 55000, np.nan, 100000],
    'score': [1, np.nan, 3, 4, 5],
    'gender': ['Male', 'Female', None, 'Male', 'Female'],
    'city': ['New York', np.nan, 'Los Angeles', 'Chicago', None]
})

# Impute missing values using the combined function
df_sample = mark_missing_values(
    df_sample,
    numerical_columns=['age'],
    categorical_columns=['gender'],
    numerical_placeholder=999,
    categorical_placeholder='missing'
)

df_sample

   └── Imputing missing values in numerical columns: ['age'] with placeholder: 999
   └── Imputing missing values in categorical columns: ['gender'] with placeholder: 'missing'

     age    income  score   gender         city
0   25.0   50000.0    1.0     Male     New York
1   30.0   60000.0    NaN   Female          NaN
2  999.0   55000.0    3.0  missing  Los Angeles
3   40.0       NaN    4.0     Male      Chicago
4  999.0  100000.0    5.0   Female         None

---
---
# **🧼 Numerical Issues**

---
## └─ **Get absolute values**

In [18]:
def get_absolute_values(df, columns=[]):
    print(f"   └── Taking absolute values for columns: {columns}")
    df = df.copy()
    for col in columns:
        if col in df.columns and pd.api.types.is_numeric_dtype(df[col]):
            df[col] = df[col].abs()
    return df

In [19]:
df_sample = pd.DataFrame({
    'age': [25, -30, 45, -50, 60],
    'income': [-50000, 60000, -55000, 70000, -100000],
    'score': [1, -2, 3, -4, 5],
    'gender': ['Male', 'Female', 'Female', 'Male', 'Male']  # non-numeric column remains unchanged
})

df_sample = get_absolute_values(df_sample, columns=['age', 'score'])
df_sample

   └── Taking absolute values for columns: ['age', 'score']

   age  income  score  gender
0   25  -50000      1    Male
1   30   60000      2  Female
2   45  -55000      3  Female
3   50   70000      4    Male
4   60 -100000      5    Male

---
---
# **🧼 Categorical Issues**

---
### └─ **Map values**

In [20]:
def map_values(df, mapping_dict):
    print(f"   └── Mapping values for columns: {list(mapping_dict.keys())}")
    df = df.copy()
    columns = mapping_dict.keys()
    for col in columns:
        if col in df.columns and col in mapping_dict:
            df[col] = df[col].map(mapping_dict[col]).fillna(df[col])
    return df

In [21]:
df_sample = pd.DataFrame({
    'Subscription Status': ['yes', 'no', 'no', 'yes'],
    'Gender': ['Male', 'Female', 'Female', 'Male'],
    'Age': [25, 30, 22, 40]
})

mapping = {
    'Subscription Status': {'yes': 1, 'no': 0},
    'Gender': {'Male': 0, 'Female': 1}
}

df_sample = map_values(df_sample, mapping)
df_sample

   └── Mapping values for columns: ['Subscription Status', 'Gender']

   Subscription Status  Gender  Age
0                    1       0   25
1                    0       1   30
2                    0       1   22
3                    1       0   40

---
### └─ **Convert test to lowercase**

In [22]:
def convert_text_to_lowercase(df, columns=[]):
    print(f"   └── Converting text to lowercase for columns: {columns}")
    df = df.copy()
    for col in columns:
        if col in df.columns and df[col].dtype == 'object':
            df[col] = df[col].str.lower()
    return df

In [23]:
df_sample = pd.DataFrame({
    'Name': ['Alice', 'BOB', 'Charlie'],
    'City': ['New York', 'LONDON', 'ToKyo'],
    'Age': [25, 30, 22]
})

df_sample = convert_text_to_lowercase(df_sample, columns=['Name'])
df_sample

   └── Converting text to lowercase for columns: ['Name']

      Name      City  Age
0    alice  New York   25
1      bob    LONDON   30
2  charlie     ToKyo   22

---
### └─ **Replace character**

In [24]:
def replace_character_in_columns(df, to_replace, replacement, columns=[]):
    print(f"   └── Replacing '{to_replace}' with '{replacement}' in columns: {columns}")
    df = df.copy()
    for col in columns:
        if col in df.columns and df[col].dtype == 'object':
            df[col] = df[col].str.replace(to_replace, replacement, regex=False)
    return df

In [ ]:
df_sample = pd.DataFrame({
    'name': ['Alice Smith', 'Bob.Jones', 'Charlie.Lane'],
    'city': ['New York', 'Los_Angeles', 'San_Francisco']
})

df_sample = replace_character_in_columns(df_sample, to_replace='.', replacement=' ', columns=['name'])
df_sample

   └── Replacing '.' with ' ' in columns: ['name']

           name           city
0   Alice Smith       New York
1     Bob Jones    Los_Angeles
2  Charlie Lane  San_Francisco

:

---
---
---